test_that("when cross selection is zero is the same as the original", {
  expect_equal(run_simulation_intervention_test_mixtures_cross_selection(number.of.insecticides = 2,
                                                                         exposure.scaling.factor = 10,
                                                                         nsim = 1,
                                                                         minimum.insecticide.resistance.heritability = 1,
                                                                         maximum.insecticide.resistance.heritability = 1,
                                                                         minimum.male.insecticide.exposure = 1,
                                                                         maximum.male.insecticide.exposure = 1,
                                                                         minimum.female.insecticide.exposure = 1,
                                                                         maximum.female.insecticide.exposure = 1,
                                                                         resistance.cost = 0,
                                                                         starting.treatment.site.intensity = 0,
                                                                         starting.refugia.intensity = 0,
                                                                         min.intervention.coverage = 0.7,
                                                                         max.intervention.coverage = 0.7,
                                                                         min.dispersal.rate = 0.1,
                                                                         max.dispersal.rate = 0.1,
                                                                         maximum.generations = 500,
                                                                         irm.deployment.strategy = "mixtures", #single, mixtures
                                                                         mixture.strategy = "mix.sequential.discrete", #can be: random.mixtures; pyrethroid.plus; mix.sequential.continous; mix.sequential.discrete
                                                                         irm.switch.strategy = "sequence", #will be sequence or rotation;default should be sequence
                                                                         half.population.bioassay.survival.resistance = 900,
                                                                         withdrawal.threshold.value = 0.1, #this is the survival proportion in a bioassay that would withdraw the insecticide from the arsenal
                                                                         return.threshold.value = 0.05, #this is the survival proportion in a bioassay that would return insecticide to arsenal
                                                                         deployment.frequency = 10, #Number of mosquito generations between choosing insecticides (note, 1 year is 10 generations)
                                                                         maximum.resistance.value = 25000,
                                                                         min.cross.selection = 0,
                                                                         max.cross.selection = 0,
                                                                         conversion.factor = 0.48,
                                                                         intercept = 0.15), 
               run_simulation_intervention_test_mixtures(number.of.insecticides = 2,
                                                                         exposure.scaling.factor = 10,
                                                                         nsim = 1,
                                                                         minimum.insecticide.resistance.heritability = 1,
                                                                         maximum.insecticide.resistance.heritability = 1,
                                                                         minimum.male.insecticide.exposure = 1,
                                                                         maximum.male.insecticide.exposure = 1,
                                                                         minimum.female.insecticide.exposure = 1,
                                                                         maximum.female.insecticide.exposure = 1,
                                                                         resistance.cost = 0,
                                                                         starting.treatment.site.intensity = 0,
                                                                         starting.refugia.intensity = 0,
                                                                         min.intervention.coverage = 0.7,
                                                                         max.intervention.coverage = 0.7,
                                                                         min.dispersal.rate = 0.1,
                                                                         max.dispersal.rate = 0.1,
                                                                         maximum.generations = 500,
                                                                         irm.deployment.strategy = "mixtures", #single, mixtures
                                                                         mixture.strategy = "mix.sequential.discrete", #can be: random.mixtures; pyrethroid.plus; mix.sequential.continous; mix.sequential.discrete
                                                                         irm.switch.strategy = "sequence", #will be sequence or rotation;default should be sequence
                                                                         half.population.bioassay.survival.resistance = 900,
                                                                         withdrawal.threshold.value = 0.1, #this is the survival proportion in a bioassay that would withdraw the insecticide from the arsenal
                                                                         return.threshold.value = 0.05, #this is the survival proportion in a bioassay that would return insecticide to arsenal
                                                                         deployment.frequency = 10, #Number of mosquito generations between choosing insecticides (note, 1 year is 10 generations)
                                                                         maximum.resistance.value = 25000,
                                                                         conversion.factor = 0.48,
                                                                         intercept = 0.15))
})
