sim.array = create_starting_array(n.insecticides = 2,
                                  maximum.generations = 10)

sim.array["treatment", 1, 5] = 100
sim.array["treatment", 2, 5] = 100

cs.matrix = make_cross_selection_matrix(number.of.insecticides = 2,
                                        min.cross.selection = 0,
                                        max.cross.selection = 0)



test_that("coverage 1, dispersal 0, FALSE == TRUE", {
  expect_equal(insecticide_deployed_migration_mixtures_special_cases(exposure.scaling.factor = 10,
                                                                     nsim = 1, 
                                                                     minimum.insecticide.resistance.heritability = 0.3, 
                                                                     maximum.insecticide.resistance.heritability = 0.3,
                                                                     minimum.male.insecticide.exposure = 1,
                                                                     maximum.male.insecticide.exposure = 1, 
                                                                     minimum.female.insecticide.exposure = 1, 
                                                                     maximum.female.insecticide.exposure = 1,
                                                                     resistance.cost = 0,
                                                                     initial.resistance.intensity = 0,
                                                                     intensity.to.other.mixture.part = 0,
                                                                     half.population.bioassay.survival.resistance = 900,
                                                                     currently.deployed.insecticide = 1,
                                                                     cross.selection.matrix = cs.matrix,
                                                                     initial.refugia.resistance = 0,
                                                                     min.intervention.coverage = 1, 
                                                                     max.intervention.coverage = 1, 
                                                                     min.dispersal.rate = 0,
                                                                     max.dispersal.rate = 0,
                                                                     number.of.insecticides = 2,
                                                                     conversion.factor = 0.48,
                                                                     intercept = 0.15,
                                                                     tracked.insecticide.efficacy = 1,
                                                                     other.insecticide.in.mixture = 2,
                                                                     efficacy.of.other.insecticide = 2,
                                                                     insecticide.suppression = "FALSE",
                                                                     current.generation = 6,
                                                                     sim.array = sim.array), 
               insecticide_deployed_migration_mixtures_special_cases(exposure.scaling.factor = 10,
                                                                     nsim = 1, 
                                                                     minimum.insecticide.resistance.heritability = 0.3, 
                                                                     maximum.insecticide.resistance.heritability = 0.3,
                                                                     minimum.male.insecticide.exposure = 1,
                                                                     maximum.male.insecticide.exposure = 1, 
                                                                     minimum.female.insecticide.exposure = 1, 
                                                                     maximum.female.insecticide.exposure = 1,
                                                                     resistance.cost = 0,
                                                                     initial.resistance.intensity = 0,
                                                                     intensity.to.other.mixture.part = 0,
                                                                     half.population.bioassay.survival.resistance = 900,
                                                                     currently.deployed.insecticide = 1,
                                                                     cross.selection.matrix = cs.matrix,
                                                                     initial.refugia.resistance = 0,
                                                                     min.intervention.coverage = 1, 
                                                                     max.intervention.coverage = 1, 
                                                                     min.dispersal.rate = 0,
                                                                     max.dispersal.rate = 0,
                                                                     number.of.insecticides = 2,
                                                                     conversion.factor = 0.48,
                                                                     intercept = 0.15,
                                                                     tracked.insecticide.efficacy = 1,
                                                                     other.insecticide.in.mixture = 2,
                                                                     efficacy.of.other.insecticide = 2,
                                                                     insecticide.suppression = "TRUE",
                                                                     current.generation = 6,
                                                                     sim.array = sim.array))
})
