test_that("cross selection zero same as original - sequences", {
  expect_equal(get_simulation_dataframe(run_simulation_intervention_cross_selection(number.of.insecticides = 2,
                                                           exposure.scaling.factor = 10,
                                                           nsim = 1,
                                                           minimum.insecticide.resistance.heritability = 0.30,
                                                           maximum.insecticide.resistance.heritability = 0.30,
                                                           minimum.male.insecticide.exposure = 0.7,
                                                           maximum.male.insecticide.exposure = 0.7,
                                                           minimum.female.insecticide.exposure = 0.7,
                                                           maximum.female.insecticide.exposure = 0.7,
                                                           resistance.cost = 0,
                                                           starting.treatment.site.intensity = 0,
                                                           starting.refugia.intensity = 0,
                                                           min.intervention.coverage = 0.7,
                                                           max.intervention.coverage = 0.7,
                                                           min.dispersal.rate = 0.3,
                                                           max.dispersal.rate = 0.3,
                                                           maximum.generations = 100,
                                                           irm.strategy = "sequence", 
                                                           half.population.bioassay.survival.resistance = 900,
                                                           withdrawal.threshold.value = 0.1, 
                                                           return.threshold.value = 0.05, 
                                                           deployment.frequency = 10, 
                                                           maximum.resistance.value = 25000,
                                                           min.cross.selection = 0,
                                                           max.cross.selection = 0), number.of.insecticides = 2,
                                        maximum.generations = 100), get_simulation_dataframe(run_simulation_intervention(number.of.insecticides = 2,
                                                                                                                                         exposure.scaling.factor = 10,
                                                                                                                                         nsim = 1,
                                                                                                                                         minimum.insecticide.resistance.heritability = 0.30,
                                                                                                                                         maximum.insecticide.resistance.heritability = 0.30,
                                                                                                                                         minimum.male.insecticide.exposure = 0.7,
                                                                                                                                         maximum.male.insecticide.exposure = 0.7,
                                                                                                                                         minimum.female.insecticide.exposure = 0.7,
                                                                                                                                         maximum.female.insecticide.exposure = 0.7,
                                                                                                                                         resistance.cost = 0,
                                                                                                                                         starting.treatment.site.intensity = 0,
                                                                                                                                         starting.refugia.intensity = 0,
                                                                                                                                         min.intervention.coverage = 0.7,
                                                                                                                                         max.intervention.coverage = 0.7,
                                                                                                                                         min.dispersal.rate = 0.3,
                                                                                                                                         max.dispersal.rate = 0.3,
                                                                                                                                         maximum.generations = 100,
                                                                                                                                         irm.strategy = "sequence", 
                                                                                                                                         half.population.bioassay.survival.resistance = 900,
                                                                                                                                         withdrawal.threshold.value = 0.1, 
                                                                                                                                         return.threshold.value = 0.05, 
                                                                                                                                         deployment.frequency = 10, 
                                                                                                                                         maximum.resistance.value = 25000), number.of.insecticides = 2,
                                                                                             maximum.generations = 100))
})


test_that("cross selection zero same as original - rotations", {
  expect_equal(get_simulation_dataframe(run_simulation_intervention_cross_selection(number.of.insecticides = 2,
                                                                                    exposure.scaling.factor = 10,
                                                                                    nsim = 1,
                                                                                    minimum.insecticide.resistance.heritability = 0.30,
                                                                                    maximum.insecticide.resistance.heritability = 0.30,
                                                                                    minimum.male.insecticide.exposure = 0.7,
                                                                                    maximum.male.insecticide.exposure = 0.7,
                                                                                    minimum.female.insecticide.exposure = 0.7,
                                                                                    maximum.female.insecticide.exposure = 0.7,
                                                                                    resistance.cost = 0,
                                                                                    starting.treatment.site.intensity = 0,
                                                                                    starting.refugia.intensity = 0,
                                                                                    min.intervention.coverage = 0.7,
                                                                                    max.intervention.coverage = 0.7,
                                                                                    min.dispersal.rate = 0.3,
                                                                                    max.dispersal.rate = 0.3,
                                                                                    maximum.generations = 100,
                                                                                    irm.strategy = "rotation", 
                                                                                    half.population.bioassay.survival.resistance = 900,
                                                                                    withdrawal.threshold.value = 0.1, 
                                                                                    return.threshold.value = 0.05, 
                                                                                    deployment.frequency = 10, 
                                                                                    maximum.resistance.value = 25000,
                                                                                    min.cross.selection = 0,
                                                                                    max.cross.selection = 0), number.of.insecticides = 2,
                                        maximum.generations = 100), get_simulation_dataframe(run_simulation_intervention(number.of.insecticides = 2,
                                                                                                                         exposure.scaling.factor = 10,
                                                                                                                         nsim = 1,
                                                                                                                         minimum.insecticide.resistance.heritability = 0.30,
                                                                                                                         maximum.insecticide.resistance.heritability = 0.30,
                                                                                                                         minimum.male.insecticide.exposure = 0.7,
                                                                                                                         maximum.male.insecticide.exposure = 0.7,
                                                                                                                         minimum.female.insecticide.exposure = 0.7,
                                                                                                                         maximum.female.insecticide.exposure = 0.7,
                                                                                                                         resistance.cost = 0,
                                                                                                                         starting.treatment.site.intensity = 0,
                                                                                                                         starting.refugia.intensity = 0,
                                                                                                                         min.intervention.coverage = 0.7,
                                                                                                                         max.intervention.coverage = 0.7,
                                                                                                                         min.dispersal.rate = 0.3,
                                                                                                                         max.dispersal.rate = 0.3,
                                                                                                                         maximum.generations = 100,
                                                                                                                         irm.strategy = "rotation", 
                                                                                                                         half.population.bioassay.survival.resistance = 900,
                                                                                                                         withdrawal.threshold.value = 0.1, 
                                                                                                                         return.threshold.value = 0.05, 
                                                                                                                         deployment.frequency = 10, 
                                                                                                                         maximum.resistance.value = 25000), number.of.insecticides = 2,
                                                                                             maximum.generations = 100))
})
