test_that("when all survive other mixture same as if only one insecticide", {
  expect_equal(insecticide_deployed_selection_cost_mixture_cross_selection(exposure.scaling.factor = 10,
                                                                           nsim = 1, 
                                                                           minimum.insecticide.resistance.heritability = 1, 
                                                                           maximum.insecticide.resistance.heritability = 1,
                                                                           minimum.male.insecticide.exposure = 1,
                                                                           maximum.male.insecticide.exposure = 1, 
                                                                           minimum.female.insecticide.exposure = 1, 
                                                                           maximum.female.insecticide.exposure = 1,
                                                                           resistance.cost = 0,
                                                                           initial.resistance.intensity = 0,
                                                                           intensity.to.other.mixture.part = 0,
                                                                           half.population.bioassay.survival.resistance = 900,
                                                                           currently.deployed.insecticide = 1,
                                                                           cross.selection.matrix = make_cross_selection_matrix(number.of.insecticides = 2,
                                                                                                                                min.cross.selection = 0,
                                                                                                                                max.cross.selection = 0),
                                                                           number.of.insecticides = 2,
                                                                           conversion.factor = 1,
                                                                           intercept = 1), insecticide_deployed_selection_cost(exposure.scaling.factor = 10,
                                                                                                                               nsim = 1, 
                                                                                                                               minimum.insecticide.resistance.heritability = 1, 
                                                                                                                               maximum.insecticide.resistance.heritability = 1,
                                                                                                                               minimum.male.insecticide.exposure = 1,
                                                                                                                               maximum.male.insecticide.exposure = 1, 
                                                                                                                               minimum.female.insecticide.exposure = 1, 
                                                                                                                               maximum.female.insecticide.exposure = 1,
                                                                                                                               resistance.cost = 0,
                                                                                                                               initial.resistance.intensity = 0))
})
